### PR TITLE
New Dragon models

### PR DESCRIPTION
**Pull request by NightFuryGaming**
# Pull Request Name (Make it short and descriptive)

i think you guys if you have time to make new models for night fury or skrill bicause they look almost the same and can you make rare chance of spawning ALPHA TOOTHLESS or you need to do something else to get him ?
## Problem

Skrill and NF look allmost the same and NF doesnt look that mutch like an Night Fury but model is still awesome
## Solution

do more details into NF and maybe add alpha nf
## Note

Your mod is exelent but it crashes with some mods

### CODE REVIEW

**Comment by Spartan322** [comment]
This branch is nowhere near ready to be merged. Why did you start a PR for it?

As for the description, we are not gonna work on improving the original dragons for a while (we have a lot of improvements planned, but remember, we don't plan to make it look outside of minecraft, it will still be required to look like it belongs in minecraft), and I am not allowing natural spawning of Night Furys at all, that must be spawned on it own (and later in story mode akin to what happen in the original first movie)

**Comment by NightFuryGaming** [comment]
no i wasnt asking for natural spawning of NF i was asking if i you can do an update where you add alpha toothless  but theres a rare chance geting him by spawning him with an spawn egg

**Comment by NightFuryGaming** [comment]
and hey spartan332 do you have skype? and if you do can i add you

**Comment by Spartan322** [comment]
Do you use Discord? I hate and avoid skype, and Discord has almost everything that skype does only done better and with more.

**Comment by NightFuryGaming** [comment]
i use it i can add you right now
if you want

**Comment by Spartan322** [comment]
Spartan322#4657 (I'm erasing that in 1 minute)

**Comment by NightFuryGaming** [comment]
k copyed

**Comment by NightFuryGaming** [comment]
the invite expired?

**Comment by NightFuryGaming** [comment]
heres an instant invite https://discord.gg/AvC9t deleting in 1 min

**Pull request closed without merging**
